version: '3.8'

services:
 simple-fastapi-server:
  build:
   context: .
  ports:
  - "8000:5000"
  volumes:
  - ./:/app

 mysqldb:
  image: mysql:5.7.42-debian
  ports:
  - "3366:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=p@ssw0rd1
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: